#!/usr/bin/env python3
"""
sweep -- drive pattern_lab over the corpus and reduce its output to the tuning
tables.

Every number the detector tuning rests on is produced by a subcommand here, so
the command is the provenance. Nothing is written down that cannot be
regenerated by re-running the line that produced it.

Stdlib only, deliberately. This box has no numpy on either interpreter, and a
tool whose job is to still run in a year should not acquire a dependency in
order to compute a percentile.

  ./sweep.py manifest                       the corpus, with sha256s
  ./sweep.py control                        (re)generate the negative control
  ./sweep.py baseline                       reproduce the hop-1024 record
  ./sweep.py sweep --detector boom          the flux floor ladder
  ./sweep.py hist                           BEAT_HIST, both axes
  ./sweep.py segments                       propose the zabumba segment table
  ./sweep.py label                          candidates and a click track
  ./sweep.py instants                       boom instants, hop 1024 vs 512
"""

import argparse
import concurrent.futures
import hashlib
import math
import os
import random
import shutil
import struct
import subprocess
import sys
import tempfile
import wave
from pathlib import Path

## @brief This file's directory; also where the checked-in tables live.
HERE = Path(__file__).resolve().parent
## @brief The dancefloor tree.
ROOT = HERE.parent.parent
## @brief The harness this drives.
LAB = ROOT / "tools" / "pattern_lab"

## @brief Lossless tracks, and the set the record was measured over.
ANCHOR_DIR = Path.home() / "dancefloor-tracks"
## @brief The wider lossy set, decoded on first use.
BREADTH_DIR = Path.home() / "Music" / "forro"
## @brief Isolated zabumba recordings, used in cut segments rather than whole.
ZABUMBA_DIR = Path.home() / "Music" / "zabumba"
## @brief Where decodes, cuts and built binaries are kept. DF_TUNING_CACHE
#         overrides it.
CACHE = Path(os.environ.get("DF_TUNING_CACHE", Path.home() / ".cache" / "dancefloor-tuning"))

# The zabumba material is cut into labelled segments rather than used whole:
# two of the six recordings are lessons, and one carries half a minute of pure
# talking that is worth keeping on purpose as a negative control. The tables
# are checked in beside this file because a segment boundary is a tuning input
# like any other -- `./sweep.py segments` shows how they were proposed, and
# what is checked in is what a human then confirmed by ear.

## @brief Segment boundaries, hand-confirmed. Written by hand from the output
#         of cmd_segments().
ZAB_SEGMENTS = HERE / "zabumba_segments.csv"
## @brief Stroke instants and classes, hand-confirmed against cmd_label()'s
#         click tracks. Absent until that pass has been done.
ZAB_LABELS = HERE / "zabumba_labels.csv"

## @brief df::RATE. Every decode is pinned to it.
RATE = 44100

## @brief The decode command, as a format template.
#
# Pinned to the firmware's rate and channel count rather than left to follow
# the source: pattern_lab analyses whatever rate the file carries, so a 48 kHz
# decode would move every band edge relative to the tuning.
FFMPEG = ["ffmpeg", "-v", "error", "-i", "{src}",
          "-ar", str(RATE), "-ac", "2", "-c:a", "pcm_s16le", "-y", "{dst}"]

## @brief How near the threshold counts as marginal, as a fraction of it.
#
# The firmware's own marginal test, from visualiser.cpp, counted PER FRAME.
# Per boom it would read as a threefold regression where there is none: the
# frame count doubled when the hop halved while the refractory period held the
# boom count nearly constant.
MARGIN = 0.1


class Track:
    """
    @brief One thing to measure: a whole recording, or a cut segment of one.
    """
    def __init__(self, label, source, wav, group, span=None):
        """
        @brief Build one.
        @param label   How it appears in a table.
        @param source  The file it came from, whatever container that was.
        @param wav     The decoded WAV pattern_lab is actually run over. The
                       same path as @p source for a lossless whole track.
        @param group   Which set it belongs to; the tables are grouped by it.
        @param span    (start_s, end_s) for a cut segment, else None.
        """
        ## @brief How this appears in a table.
        self.label = label
        ## @brief The file it came from, whatever container that was.
        self.source = source
        ## @brief The decoded WAV pattern_lab is run over.
        self.wav = wav
        ## @brief Which set it belongs to; the tables group by it.
        self.group = group
        ## @brief (start_s, end_s) for a cut segment, else None.
        self.span = span


def sha256(path):
    """
    @brief Hex sha256 of a file, read a megabyte at a time.
    @param path  The file.
    @return The digest.
    """
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def wav_info(path):
    """
    @brief A WAV's rate and duration.
    @param path  The file.
    @return (rate_hz, seconds).
    """
    with wave.open(str(path), "rb") as w:
        return w.getframerate(), w.getnframes() / w.getframerate()


def decode(src, dst):
    """
    @brief Decode anything ffmpeg reads into a WAV at the firmware's rate.
    @param src  The source file.
    @param dst  Where to write; parents are created, an existing file is
                overwritten.
    """
    dst.parent.mkdir(parents=True, exist_ok=True)
    cmd = [a.format(src=str(src), dst=str(dst)) for a in FFMPEG]
    subprocess.run(cmd, check=True)


def corpus(groups, quiet=False):
    """
    @brief The tracks in the named groups, decoding and caching as needed.

    The anchor set is read from the top level of its directory only. A nested
    xotes/ is excluded on purpose: most of its files are 44-byte headers with
    no audio and much of the rest is advertising, so an average over them
    would not mean anything.

    @param groups  Any of "anchor", "breadth", "control", "zabumba",
                   "zabumba-speech".
    @param quiet   Suppress the "decoding N tracks" note on stderr.
    @return A list of Track.
    """
    out = []
    if "anchor" in groups:
        # Top level only; see the docstring for why a nested xotes/ is out.
        for p in sorted(ANCHOR_DIR.glob("*.wav")):
            out.append(Track(p.stem, p, p, "anchor"))
    if "breadth" in groups:
        wavdir = CACHE / "wav"
        todo = []
        for p in sorted(BREADTH_DIR.glob("*.mp3")):
            dst = wavdir / (p.stem + ".wav")
            if not dst.exists():
                todo.append((p, dst))
            out.append(Track(p.stem, p, dst, "breadth"))
        if todo:
            if not quiet:
                print(f"decoding {len(todo)} tracks into {wavdir} ...", file=sys.stderr)
            with concurrent.futures.ThreadPoolExecutor(max_workers=os.cpu_count()) as ex:
                list(ex.map(lambda a: decode(*a), todo))
    if "control" in groups:
        p = CACHE / "control.wav"
        if not p.exists():
            make_control(p)
        out.append(Track("control (synthetic, no drum)", p, p, "control"))
    for g in ("zabumba", "zabumba-speech"):
        if g in groups:
            out.extend(zabumba_tracks("drum" if g == "zabumba" else "speech", g))
    return out


def zab_sources():
    """
    @brief The zabumba recordings, whatever container they arrived in.

    This is the only group with positive ground truth behind it, and the only
    one on which "did it fire on a drum stroke" is answerable at all -- on a
    full mix a rate ladder cannot tell a suppressed stroke from an absent one.
    It does not replace the anchor set, which is lossless and carries the
    comparison against the record; these are lossy rips through room and
    camera mics, and they answer a different question. Do not read one
    group's ladder as the other's.

    @return The source files, sorted.
    """
    return sorted(p for p in ZABUMBA_DIR.iterdir()
                  if p.suffix.lower() in (".opus", ".mp4", ".m4a", ".wav", ".mp3"))


def zab_full_wav(src):
    """
    @brief The whole recording at the firmware's rate, decoded once and cached.
    @param src  The source file.
    @return The cached WAV.
    """
    dst = CACHE / "wav" / "zabumba" / (src.stem + ".full.wav")
    if not dst.exists():
        decode(src, dst)
    return dst


def zab_cut(src, start, end):
    """
    @brief One segment, cut from the cached full decode and itself cached.

    Cut with the stdlib wave module rather than with ffmpeg -ss, so the
    boundary is an exact sample index rather than wherever the container's
    seek lands. ZAB_LABELS holds instants inside these cuts, so a boundary
    that moved by a few milliseconds between runs would silently shift every
    one of them.

    @param src    The source recording.
    @param start  Seconds into it.
    @param end    Seconds into it; clamped to the end of the file.
    @return The cut WAV.
    """
    dst = CACHE / "wav" / "zabumba" / f"{src.stem}.{start:g}-{end:g}.wav"
    if dst.exists():
        return dst
    full = zab_full_wav(src)
    dst.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(full), "rb") as r:
        rate, ch, w = r.getframerate(), r.getnchannels(), r.getsampwidth()
        a, b = int(start * rate), int(end * rate)
        b = min(b, r.getnframes())
        r.setpos(a)
        frames = r.readframes(max(0, b - a))
    with wave.open(str(dst), "wb") as o:
        o.setnchannels(ch)
        o.setsampwidth(w)
        o.setframerate(rate)
        o.writeframes(frames)
    return dst


def zab_segment_rows():
    """
    @brief Read the checked-in segment table.
    @return [(stem, start_s, end_s, label)], empty before the table exists.
    """
    if not ZAB_SEGMENTS.exists():
        return []
    rows = []
    for line in ZAB_SEGMENTS.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("file,"):
            continue
        stem, start, end, label = line.split(",")
        rows.append((stem, float(start), float(end), label))
    return rows


def zabumba_tracks(label, group):
    """
    @brief Cut every segment carrying one label into a Track.
    @param label  "drum" or "speech", matched against the segment table.
    @param group  The group name to tag the tracks with.
    @return A list of Track.
    """
    by_stem = {p.stem: p for p in zab_sources()}
    out = []
    for stem, start, end, lab in zab_segment_rows():
        if lab != label:
            continue
        src = by_stem.get(stem)
        if src is None:
            raise SystemExit(f"{ZAB_SEGMENTS}: no recording named {stem!r} in {ZABUMBA_DIR}")
        out.append(Track(f"{stem} [{start:g}-{end:g}]", src,
                         zab_cut(src, start, end), group, (start, end)))
    return out


def make_control(path, seconds=30):
    """
    @brief Synthesise the negative control: music with no drum anywhere in it.

    This is the acceptance test at the low end of the ladder. Without it
    "lower floor -> more booms" has no cost attached, because nothing says
    what the extra sensitivity is firing on.

    It is not silence with a beep. The bass CHANGES -- a left hand moving
    every two bars gives band 0 genuine rises to be wrong about -- and a
    triangle puts continuous energy in the top band at eighth-note rate, which
    is exactly what the boom detector exists to ignore. A floor that fires
    here is following the music rather than the drum.

    Two details in the synthesis are corrections rather than choices, and both
    are load-bearing. Phase is INTEGRATED rather than computed as f*t, and the
    triangle gets a 3 ms attack rather than being switched on: a step
    discontinuity is broadband, so a note change or a gated 6.3 kHz sine dumps
    energy straight into band 0 and the detector fires on it -- correctly. And
    the level is calibrated rather than picked, to put band 0's median where
    the anchor corpus sits; ten times that and a steady sine's own leakage
    ripple swings the band by the whole flux floor, so the control measures
    its own synthesis instead of the detector.

    @param path     Where to write the WAV; parents are created.
    @param seconds  How long to make it.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    rng = random.Random(20260804)              # seeded: the sha256 is in the manifest
    n = seconds * RATE
    bass_notes = [55.0, 61.74, 49.0, 65.41]    # A1, B1, G1, C2 -- inside band 0
    frames = bytearray()
    phase_bass = 0.0
    phase_tri = 0.0
    for i in range(n):
        t = i / RATE
        # A note every 500 ms, each with a 30 ms attack and a slow decay. This
        # is the part that gives the control teeth: a bass note starting IS a
        # rise in band 0, and it is not a drum. A drone would have been silent
        # at every floor and would have proved nothing. 30 ms is a plucked or
        # bowed bass; a zabumba's mallet stroke is nearer 5, and telling those
        # apart is what the floor is being asked to do.
        note_t = t % 0.5
        f0 = bass_notes[int(t / 0.5) % len(bass_notes)]
        note_env = min(1.0, note_t / 0.030) * math.exp(-note_t * 1.2)
        phase_bass += 2 * math.pi * f0 / RATE
        phase_tri += 2 * math.pi * 6300.0 / RATE
        env = 0.0137 * (0.95 + 0.05 * math.sin(2 * math.pi * 0.3 * t)) * note_env
        v = env * math.sin(phase_bass)
        v += 0.5 * env * math.sin(3 * phase_bass)            # reedy, not pure
        # Right hand, well above band 0.
        for h in (392.0, 493.88, 587.33):
            v += 0.05 * math.sin(2 * math.pi * h * t)
        # Triangle: eighths at 120 BPM, 3 ms attack then decay, 6.3 kHz.
        ph = t % 0.25
        if ph < 0.12:
            attack = min(1.0, ph / 0.003)
            v += 0.10 * attack * math.exp(-ph * 30.0) * math.sin(phase_tri)
        v += rng.uniform(-1.0, 1.0) * 0.0005                 # dither
        s = max(-32768, min(32767, int(v * 20000)))
        frames += struct.pack("<hh", s, s)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(bytes(frames))
    print(f"wrote {path} ({seconds} s)", file=sys.stderr)


def newest_source(*dirs):
    """
    @brief mtime of the most recently touched file that goes into a host binary.

    The caches below are keyed on (hop, hist) alone, which is not enough on
    its own: a component that grows a feature leaves every cached binary
    predating it, and a sweep run afterwards measures the previous month's
    detector while reporting it as today's. A cached artefact older than its
    sources is the one failure mode a tuning harness cannot be allowed to
    have, since nothing about the output says which code produced it.

    @param dirs  Directories to scan; each is also scanned for an include/.
    @return The newest mtime found, or 0.0 for no sources at all.
    """
    newest = 0.0
    for d in dirs:
        for pat in ("*.c", "*.cpp", "*.h", "*.hpp", "Makefile"):
            for f in list(d.glob(pat)) + list((d / "include").glob(pat)):
                newest = max(newest, f.stat().st_mtime)
    return newest


def build_lab(hop, hist=None):
    """
    @brief Build one pattern_lab per (hop, hist) and cache it.

    Cached because a sweep would otherwise rebuild the same binary once per
    row. The build is bracketed by `make clean` on both sides, since HOP and
    HIST reach the object files and a stale one would link a disagreeing
    struct.

    @param hop   DF_HOP_N to build with.
    @param hist  BEAT_HIST to build with; None leaves the header's default.
    @return Path to the cached binary.
    """
    tag = f"hop{hop}" + (f".hist{hist}" if hist else "")
    out = CACHE / "bin" / f"pattern_lab.{tag}"
    if out.exists() and out.stat().st_mtime >= newest_source(LAB, ROOT / "components" / "dancefloor_leds"):
        return out
    out.parent.mkdir(parents=True, exist_ok=True)
    args = ["make", "-C", str(LAB), f"HOP={hop}"]
    if hist:
        args.append(f"HIST={hist}")
    subprocess.run(["make", "-C", str(LAB), "clean"], check=True, stdout=subprocess.DEVNULL)
    subprocess.run(args, check=True, stdout=subprocess.DEVNULL)
    shutil.copy2(LAB / "pattern_lab", out)
    subprocess.run(["make", "-C", str(LAB), "clean"], check=True, stdout=subprocess.DEVNULL)
    return out


def run_lab(binary, wav, csv, flags=()):
    """
    @brief Run pattern_lab over one file and write its per-frame CSV.
    @param binary  Which build to run.
    @param wav     The track.
    @param csv     Where the trace goes.
    @param flags   Extra arguments, typically a tuning override.
    """
    subprocess.run([str(binary), str(wav), "--no-tty", "--csv", str(csv), *flags],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def run_dump(binary, wav, prefix):
    """
    @brief Run pattern_lab over one file and write its per-frame binary dump.
    @param binary  Which build to run.
    @param wav     The track.
    @param prefix  The PREFIX the four dump files are written under.
    """
    subprocess.run([str(binary), str(wav), "--no-tty", "--dump", str(prefix)],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def read_band_dump(prefix):
    """
    @brief Frame::band per frame, from a pattern_lab --dump.

    The other reader of this format is tools/pattern_lab/dump_load.py, which
    needs numpy and says so. This one does not: four float32 per frame is a
    struct.unpack, and everything here has to keep running on the stdlib.
    Both check the size against the .meta sidecar, so a truncated file is
    caught here for the same reason it is caught there.

    @param prefix  The PREFIX passed to --dump.
    @return (meta, band), band being a list of four-float tuples per frame.
    """
    meta = {}
    for line in Path(str(prefix) + ".meta").read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            meta[k.strip()] = v.strip()
    frames, bins = int(meta["frames"]), int(meta["band_bins"])
    raw = Path(str(prefix) + ".band.bin").read_bytes()
    want = frames * bins * 4
    if len(raw) != want:
        raise SystemExit(f"{prefix}.band.bin: {len(raw)} bytes, expected {want}")
    flat = struct.unpack(f"<{frames * bins}f", raw)
    return meta, [flat[i * bins:(i + 1) * bins] for i in range(frames)]


def metrics(csv):
    """
    @brief Everything a table needs, from one pass over a trace.

    Counted from the CSV rather than from pattern_lab's stderr summary, so the
    boom count and the marginal rate are known to come from the same frames.

    @param csv  A pattern_lab --csv.
    @return A dict of counts, rates, flux percentiles and firing instants.
    """
    frames = 0
    booms = onsets = 0
    marg_boom = marg_beat = 0
    boom_flux = []
    boom_thr = []
    boom_at = []
    onset_at = []
    with open(csv) as f:
        for line in f:
            if line[0] == "#" or line[0] == "b":       # header comment, column header
                continue
            c = line.rstrip("\n").split(",")
            if len(c) < 14:
                continue
            frames += 1
            t = float(c[1])
            flux, thr = float(c[6]), float(c[7])
            bflux, bthr = float(c[10]), float(c[11])
            if c[8] == "1":
                onsets += 1
                onset_at.append(t)
            if c[12] == "1":
                booms += 1
                boom_at.append(t)
            if bthr > 0 and abs(bflux - bthr) < MARGIN * bthr:
                marg_boom += 1
            if thr > 0 and abs(flux - thr) < MARGIN * thr:
                marg_beat += 1
            boom_flux.append(bflux)
            boom_thr.append(bthr)
    return {
        "frames": frames,
        "booms": booms,
        "onsets": onsets,
        "marginal_boom": marg_boom / frames if frames else 0.0,
        "marginal_beat": marg_beat / frames if frames else 0.0,
        "flux_p50": pctile(boom_flux, 0.50),
        "flux_p90": pctile(boom_flux, 0.90),
        "flux_p99": pctile(boom_flux, 0.99),
        "thr_sd": sd(boom_thr),
        "boom_at": boom_at,
        "onset_at": onset_at,
    }


def pctile(v, p):
    """
    @brief A percentile, by nearest rank.
    @param v  The values; not modified.
    @param p  0..1.
    @return The value at that rank, or 0.0 for an empty input.
    """
    if not v:
        return 0.0
    s = sorted(v)
    i = max(0, math.ceil(p * len(s)) - 1)
    return s[i]


def sd(v):
    """
    @brief Population standard deviation.
    @param v  The values.
    @return The deviation, or 0.0 for fewer than two values.
    """
    if len(v) < 2:
        return 0.0
    m = sum(v) / len(v)
    return math.sqrt(sum((x - m) ** 2 for x in v) / len(v))


def per_min(count, wav):
    """
    @brief Turn a count over a whole file into a rate per minute.
    @param count  How many.
    @param wav    The file they were counted over.
    @return Events per minute, or 0.0 for an empty file.
    """
    _, secs = wav_info(wav)
    return count * 60.0 / secs if secs else 0.0


def measure(track, binary, flags=()):
    """
    @brief Run one track through pattern_lab and reduce it to one row.
    @param track   What to measure.
    @param binary  Which build to run.
    @param flags   Extra arguments, typically a tuning override.
    @return metrics(), plus the duration, the two per-minute rates, and the
            track's label and group.
    """
    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False) as tf:
        csv = Path(tf.name)
    try:
        run_lab(binary, track.wav, csv, flags)
        m = metrics(csv)
    finally:
        csv.unlink(missing_ok=True)
    _, secs = wav_info(track.wav)
    m["secs"] = secs
    m["booms_min"] = m["booms"] * 60.0 / secs if secs else 0.0
    m["onsets_min"] = m["onsets"] * 60.0 / secs if secs else 0.0
    m["label"] = track.label
    m["group"] = track.group
    return m


def measure_all(tracks, binary, flags=(), jobs=None):
    """
    @brief measure() over a list of tracks, in parallel.
    @param tracks  What to measure.
    @param binary  Which build to run.
    @param flags   Extra arguments, passed to every run.
    @param jobs    Workers; defaults to two fewer than the CPU count, so a
                   sweep leaves the machine usable.
    @return One row per track, in order.
    """
    jobs = jobs or max(1, os.cpu_count() - 2)
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as ex:
        return list(ex.map(lambda t: measure(t, binary, flags), tracks))


def rng_str(vals, fmt="{:.0f}"):
    """
    @brief Format a min-max range for a table cell.
    @param vals  The values.
    @param fmt   Format string for each end.
    @return "lo-hi", or "-" for an empty input.
    """
    if not vals:
        return "-"
    return f"{fmt.format(min(vals))}-{fmt.format(max(vals))}"


def med(vals):
    """
    @brief The median.
    @param vals  The values.
    @return pctile(vals, 0.50).
    """
    return pctile(vals, 0.50)


def cmd_manifest(args):
    """
    @brief Print the corpus as a markdown table, with sha256s.

    A segment's source digest is shared with its siblings and so does not
    identify the material a label is keyed to; the cut's own digest does, and
    that is what the segment rows carry. The source recordings are listed
    separately underneath.

    @param args  Parsed arguments; only args.groups is read.
    """
    tracks = corpus(args.groups)
    print("| Track | Set | Source | s | Hz | sha256 |")
    print("|---|---|---|---|---|---|")
    for t in tracks:
        rate, secs = wav_info(t.wav)
        if t.span:
            kind = f"{t.source.suffix.lstrip('.')}, cut {t.span[0]:g}-{t.span[1]:g} s"
            digest = sha256(t.wav)
        else:
            kind = "wav" if t.source.suffix == ".wav" else "mp3, decoded"
            digest = sha256(t.source)
        print(f"| {t.label} | {t.group} | {kind} | {secs:.0f} | {rate} | {digest} |")
    if any(t.span for t in tracks):
        print()
        print("Segment sha256s are of the cut WAV, since the labels are instants")
        print("inside it. Source recordings:")
        print()
        print("| Recording | s | sha256 (source) |")
        print("|---|---|---|")
        for src in zab_sources():
            _, secs = wav_info(zab_full_wav(src))
            print(f"| {src.name} | {secs:.0f} | {sha256(src)} |")
    ver = subprocess.run(["ffmpeg", "-version"], capture_output=True, text=True)
    print()
    print(f"decoded with: {' '.join(FFMPEG)}")
    print(f"ffmpeg: {ver.stdout.splitlines()[0]}")


def cmd_control(args):
    """
    @brief Regenerate the negative control and print its sha256.
    @param args  Parsed arguments; unused.
    """
    make_control(CACHE / "control.wav")
    print(f"sha256 {sha256(CACHE / 'control.wav')}")


def cmd_baseline(args):
    """
    @brief The gate: reproduce the hop-1024 figures the tuning was set from.

    Nothing after this means anything if it does not land on the record, since
    a harness that disagrees with it is not measuring what the record
    measured. The expected ranges are printed beside the measured ones so the
    comparison needs no second document.

    @param args  Parsed arguments; unused, the anchor set is fixed.
    """
    lab = build_lab(1024)
    rows = measure_all(corpus(["anchor"]), lab)
    print("| Track | booms/min | onsets/min | marginal/frame | flux p50 | p90 | p99 |")
    print("|---|---|---|---|---|---|---|")
    for r in sorted(rows, key=lambda r: r["label"]):
        print(f"| {r['label']} | {r['booms_min']:.1f} | {r['onsets_min']:.1f} | "
              f"{100*r['marginal_boom']:.1f}% | {r['flux_p50']:.4f} | "
              f"{r['flux_p90']:.4f} | {r['flux_p99']:.4f} |")
    print()
    print(f"booms/min range   {rng_str([r['booms_min'] for r in rows], '{:.0f}')}   "
          f"(record: 68-134)")
    print(f"flux p90 range    {rng_str([r['flux_p90'] for r in rows], '{:.4f}')}   "
          f"(record: 0.016-0.019)")
    print(f"flux p99 range    {rng_str([r['flux_p99'] for r in rows], '{:.4f}')}   "
          f"(record: 0.038-0.131)")
    print(f"flux p50 max      {max(r['flux_p50'] for r in rows):.4f}   (record: 0.0000)")


def zab_seconds(binary, wav, window=1.0):
    """
    @brief Per-window statistics for splitting a recording into drumming and
           talking.

    Three numbers, all from Frame::band so that nothing here can measure
    something a satellite could not -- a rule, not a coincidence:

      b0    median band 0, the mallet stroke's own band
      rise  p90 of the frame-to-frame rise in band 0: transients rather than
            level, which is what separates drumming from a sustained low note
      b1    median band 1, where a voice's vowels are
      b2    median band 2, where a voice's consonants are and where the drum
            has almost nothing

    A drum passage is high `rise`; a talking passage is low `rise` with band 1
    still present, which also separates talking from the silence between
    takes. Level alone would not do it, since a ringing drum head and a
    speaking voice can share a band-0 median. b2 is the obvious choice for the
    speech half and is the wrong one: on these recordings it barely moves
    whether anyone is talking or not, while b1 moves by a factor of ten.

    @param binary  Which pattern_lab build to run.
    @param wav     The recording.
    @param window  Seconds per window.
    @return One dict per window: t, b0, b1, b2, rise.
    """
    with tempfile.TemporaryDirectory() as td:
        prefix = Path(td) / "seg"
        run_dump(binary, wav, prefix)
        meta, band = read_band_dump(prefix)
    hop, rate = int(meta["hop"]), int(meta["rate"])
    per = max(1, int(window * rate / hop))
    out = []
    for i in range(0, len(band), per):
        w = band[i:i + per]
        if len(w) < per // 2:
            break
        rises = [max(0.0, w[j][0] - w[j - 1][0]) for j in range(1, len(w))]
        out.append({
            "t": i * hop / rate,
            "b0": pctile([f[0] for f in w], 0.50),
            "b1": pctile([f[1] for f in w], 0.50),
            "b2": pctile([f[2] for f in w], 0.50),
            "rise": pctile(rises, 0.90),
        })
    return out


def cmd_segments(args):
    """
    @brief Propose the segment table, for a human to confirm by ear.

    Proposed rather than written: this classifier finds the boundaries, it is
    not evidence for them. What gets checked into ZAB_SEGMENTS is what a
    person confirmed, and that distinction is the point -- a tuning input with
    no provenance is worth nothing.

    Short interruptions inside a run are absorbed, since a bar's rest inside a
    groove is not a segment boundary and one struck drum inside a sentence is
    not a drum segment.

    @param args  Parsed arguments: hop, window, the rise and b1 thresholds,
                 the minimum run and segment lengths, and raw.
    """
    lab = build_lab(args.hop)
    print("# proposed segments -- confirm by ear before checking in")
    print(f"# rise >= {args.rise} -> drum;  rise < {args.rise} and b1 >= {args.b1} -> speech")
    print("file,start_s,end_s,label")
    for src in zab_sources():
        wav = zab_full_wav(src)
        secs = zab_seconds(lab, wav, args.window)
        if args.raw:
            print(f"# {src.stem}", file=sys.stderr)
            for r in secs:
                print(f"#   {r['t']:6.1f}  b0={r['b0']:.4f} b1={r['b1']:.4f} b2={r['b2']:.4f} "
                      f"rise={r['rise']:.4f}", file=sys.stderr)
        klass = []
        for r in secs:
            if r["rise"] >= args.rise:
                klass.append("drum")
            elif r["b1"] >= args.b1:
                klass.append("speech")
            else:
                klass.append("quiet")
        # Runs, with short interruptions absorbed -- see the docstring.
        runs = []
        for i, k in enumerate(klass):
            if runs and runs[-1][0] == k:
                runs[-1][2] = i + 1
            else:
                runs.append([k, i, i + 1])
        changed = True
        while changed:
            changed = False
            for i in range(1, len(runs) - 1):
                if (runs[i][2] - runs[i][1]) * args.window < args.min_run and \
                        runs[i - 1][0] == runs[i + 1][0]:
                    runs[i - 1][2] = runs[i + 1][2]
                    del runs[i:i + 2]
                    changed = True
                    break
        for k, a, b in runs:
            span = (b - a) * args.window
            if k == "quiet" or span < args.min_seg:
                continue
            print(f"{src.stem},{a * args.window:g},{b * args.window:g},{k}")


## @brief Two candidates closer together than this are treated as one stroke.
CAND_REFRACTORY_S = 0.060
## @brief The rise a candidate needs. Deliberately far under any shipped flux
#         floor -- rejecting is quick and hunting is not, so the human pass
#         should read a list that is too long rather than search the audio for
#         what is missing.
CAND_RISE = 0.004


def zab_candidates(binary, wav, offset=0.0):
    """
    @brief Every plausible stroke instant in one segment, with a guess at its
           class.

    Peaks in band 0's rise and in band 2's rise, merged. Both are needed: band
    0 finds the mallet stroke on the big head and band 2 finds the stick
    stroke on the thin one, and the second is the point rather than a
    distraction -- confusion between the two is the number a band-0-only
    design exists to keep small, and it cannot be computed without the stick
    strokes labelled.

    A peak has to be a local maximum over the two frames either side, so one
    stroke's attack ramp does not become four candidates; two peaks within
    CAND_REFRACTORY_S are merged as one stroke, keeping the stronger and
    letting a mallet stroke win a tie, since a mallet stroke mislabelled as a
    stick stroke is the error that costs a real detection.

    The class is a guess from which band rose more. The ear decides.

    @param binary  Which pattern_lab build to run.
    @param wav     The cut segment.
    @param offset  Seconds the segment starts at, so the instants come out
                   absolute within the full recording.
    @return [(t_s, "boom"|"tapa")], in time order.
    """
    with tempfile.TemporaryDirectory() as td:
        prefix = Path(td) / "cand"
        run_dump(binary, wav, prefix)
        meta, band = read_band_dump(prefix)
    hop, rate = int(meta["hop"]), int(meta["rate"])
    rise = [[0.0] * 4]
    for i in range(1, len(band)):
        rise.append([max(0.0, band[i][k] - band[i - 1][k]) for k in range(4)])

    peaks = []
    for k in (0, 2):
        for i in range(2, len(rise) - 2):
            v = rise[i][k]
            if v < CAND_RISE:
                continue
            # A local maximum over the window either side, so one stroke's
            # attack ramp does not become four candidates.
            if any(rise[j][k] > v for j in range(i - 2, i + 3) if j != i):
                continue
            peaks.append((i, k, v))
    peaks.sort()

    out = []
    for i, k, v in peaks:
        t = offset + i * hop / rate
        # Same stroke seen in both bands, or the tail of the previous one.
        if out and t - out[-1][0] < CAND_REFRACTORY_S:
            if v > out[-1][2] or k == 0:
                out[-1] = (out[-1][0], k if v > out[-1][2] else out[-1][1], max(v, out[-1][2]))
            continue
        out.append((t, k, v))
    return [(t, "boom" if k == 0 else "tapa") for t, k, _ in out]


def write_click_track(wav, cands, offset, dst):
    """
    @brief The segment in one ear, a click at each candidate in the other.

    The whole verification interface, and one file rather than a UI because
    the judgement being asked for -- did that click land on a stroke, and was
    it the right kind -- is a listening task. The two classes click at
    different pitches, so a mislabelled stroke is audible rather than needing
    to be looked up.

    @param wav     The cut segment; 16-bit PCM.
    @param cands   As zab_candidates() returns them.
    @param offset  The segment's start, subtracted to place the clicks.
    @param dst     Where to write the stereo result.
    """
    with wave.open(str(wav), "rb") as r:
        rate, ch, width = r.getframerate(), r.getnchannels(), r.getsampwidth()
        n = r.getnframes()
        raw = r.readframes(n)
    if width != 2:
        raise SystemExit(f"{wav}: expected 16-bit PCM")
    pcm = list(struct.unpack(f"<{len(raw) // 2}h", raw))
    left = [pcm[i * ch] for i in range(n)] if ch > 1 else pcm[:]

    right = [0] * n
    dur = int(0.004 * rate)
    for t, klass in cands:
        start = int((t - offset) * rate)
        f = 2400.0 if klass == "boom" else 5200.0
        for j in range(dur):
            i = start + j
            if 0 <= i < n:
                env = 1.0 - j / dur
                right[i] = max(-32768, min(32767,
                              right[i] + int(9000 * env * math.sin(2 * math.pi * f * j / rate))))
    with wave.open(str(dst), "wb") as o:
        o.setnchannels(2)
        o.setsampwidth(2)
        o.setframerate(rate)
        o.writeframes(struct.pack(f"<{2 * n}h",
                                  *[v for pair in zip(left, right) for v in pair]))


def read_labels():
    """
    @brief Read the hand-verified stroke table.
    @return {stem: [(t_s, class)]}, each list sorted; empty before the table
            exists.
    """
    out = {}
    if not ZAB_LABELS.exists():
        return out
    for line in ZAB_LABELS.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("file,"):
            continue
        stem, t, klass = line.rsplit(",", 2)
        out.setdefault(stem, []).append((float(t), klass))
    for v in out.values():
        v.sort()
    return out


def cmd_label(args):
    """
    @brief Generate candidates and click tracks for the human pass.

    Instants are absolute seconds into the full recording rather than offsets
    into a segment, so moving a segment boundary later does not silently shift
    every label inside it. A recording that already has labels is skipped
    unless --force.

    @param args  Parsed arguments: track, hop, out, force.
    """
    lab = build_lab(args.hop)
    have = read_labels()
    rows = [r for r in zab_segment_rows() if r[3] == "drum"]
    if args.track:
        rows = [r for r in rows if args.track.lower() in r[0].lower()]
    if not rows:
        raise SystemExit("no drum segments match --track")
    by_stem = {p.stem: p for p in zab_sources()}

    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)
    written = []
    for stem, start, end, _ in rows:
        if stem in have and not args.force:
            print(f"skip {stem} [{start:g}-{end:g}] -- already in {ZAB_LABELS.name} "
                  f"({len(have[stem])} rows); --force to regenerate", file=sys.stderr)
            continue
        src = by_stem[stem]
        wav = zab_cut(src, start, end)
        cands = zab_candidates(lab, wav, offset=start)
        click = outdir / f"{stem}.{start:g}-{end:g}.click.wav"
        write_click_track(wav, cands, start, click)
        written.append((stem, start, end, cands, click))
        print(f"{stem} [{start:g}-{end:g}]  {len(cands)} candidates  -> {click}",
              file=sys.stderr)

    if not written:
        return
    print("file,t_s,class")
    for stem, _, _, cands, _ in written:
        for t, klass in cands:
            print(f"{stem},{t:.3f},{klass}")


def cmd_sweep(args):
    """
    @brief The flux floor ladder: one row per floor per group, plus the control.
    @param args  Parsed arguments: groups, detector, hop, hist, floors.
    """
    lab = build_lab(args.hop, args.hist)
    tracks = corpus(args.groups)
    control = corpus(["control"])[0]
    key = "boom" if args.detector == "boom" else "beat"
    print(f"# {args.detector} flux floor, hop {args.hop}"
          + (f", BEAT_HIST {args.hist}" if args.hist else ""))
    print()
    print("| Floor | Set | rate/min | marginal/frame (median) | marginal range | control |")
    print("|---|---|---|---|---|---|")
    for floor in args.floors:
        flag = ["--boom-floor", str(floor)] if key == "boom" else ["--beat-floor", str(floor)]
        rows = measure_all(tracks, lab, flag)
        cr = measure(control, lab, flag)
        for group in args.groups:
            g = [r for r in rows if r["group"] == group]
            if not g:
                continue
            rate = [r["booms_min"] if key == "boom" else r["onsets_min"] for r in g]
            marg = [100 * r[f"marginal_{key}"] for r in g]
            cnt = cr["booms"] if key == "boom" else cr["onsets"]
            print(f"| {floor} | {group} | {rng_str(rate)} | {med(marg):.1f}% | "
                  f"{rng_str(marg, '{:.1f}')}% | {cnt} |")


def cmd_hist(args):
    """
    @brief BEAT_HIST on both of its axes at once.

    Left half: what the music says -- rate, marginal frames, and how noisy the
    threshold estimate is. Right half: what a lost frame costs, from converge,
    which the corpus cannot see at all. The two axes have to be read together,
    since BEAT_HIST is a frame count and the wall-clock it spans moves with
    the hop.

    @param args  Parsed arguments: groups, hop, hists, gap.
    """
    tracks = corpus(args.groups)
    print(f"# BEAT_HIST at hop {args.hop}")
    print()
    print("| HIST | span | onsets/min | booms/min | marginal beat | marginal boom "
          "| threshold sd | converge p50 | p95 | p95 ms | clean trials |")
    print("|---|---|---|---|---|---|---|---|---|---|---|")
    probe_csv = None
    for hist in args.hists:
        lab = build_lab(args.hop, hist)
        rows = measure_all(tracks, lab)
        span_ms = hist * args.hop * 1000.0 / RATE

        # One trace for the probe, written once and reused at every HIST. The
        # bands are an output of the FFT and the band edges, neither of which
        # BEAT_HIST touches, so re-deriving them per row would only introduce a
        # second thing that moves.
        probe_csv = CACHE / f"probe.hop{args.hop}.csv"
        if not probe_csv.exists():
            run_lab(lab, tracks[0].wav, probe_csv)
        conv = subprocess.run(
            [str(build_converge(hist, args.hop)), str(probe_csv),
             "--detector", "beat", "--gap", str(args.gap)],
            capture_output=True, text=True, check=True).stdout.split()
        c = dict(kv.split("=", 1) for kv in conv)

        print(f"| {hist} | {span_ms:.0f} ms | "
              f"{med([r['onsets_min'] for r in rows]):.1f} | "
              f"{med([r['booms_min'] for r in rows]):.1f} | "
              f"{med([100*r['marginal_beat'] for r in rows]):.1f}% | "
              f"{med([100*r['marginal_boom'] for r in rows]):.1f}% | "
              f"{med([r['thr_sd'] for r in rows]):.5f} | "
              f"{c['converge_p50']} | {c['converge_p95']} | {c['converge_p95_ms']} | "
              f"{c['clean_trials']} |")


def build_converge(hist, hop):
    """
    @brief Build one converge per (hist, hop) and cache it. @see build_lab
    @param hist  BEAT_HIST to build with.
    @param hop   DF_HOP_N to build with; analysis.hpp static_asserts on it.
    @return Path to the cached binary.
    """
    out = CACHE / "bin" / f"converge.hop{hop}.hist{hist}"
    if out.exists() and out.stat().st_mtime >= newest_source(HERE, ROOT / "components" / "dancefloor_leds"):
        return out
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["make", "-C", str(HERE), "clean"], check=True, stdout=subprocess.DEVNULL)
    subprocess.run(["make", "-C", str(HERE), f"HIST={hist}", f"HOP={hop}"],
                   check=True, stdout=subprocess.DEVNULL)
    shutil.copy2(HERE / "converge", out)
    subprocess.run(["make", "-C", str(HERE), "clean"], check=True, stdout=subprocess.DEVNULL)
    return out


def cmd_instants(args):
    """
    @brief Whether halving the hop is the same detector on a finer grid, or a
           different one with a similar count.

    Counts alone cannot tell those apart, since a matched count with shifted
    timing is a different detector. So every hop-1024 boom is matched to the
    nearest hop-512 boom and the distances are reported, one hop and one
    window being the two thresholds that mean something. Unmatched in the
    other direction -- a hop-512 boom with nothing near it at 1024 -- is the
    extra sensitivity, which is expected and is not a failure.

    @param args  Parsed arguments: boom_floor, hist.
    """
    flags = []
    if args.boom_floor is not None:
        flags = ["--boom-floor", str(args.boom_floor)]
    coarse = build_lab(1024, args.hist)
    fine = build_lab(512, args.hist)
    tracks = corpus(["anchor"])
    print("| Track | booms 1024 | booms 512 | within 12 ms | within 23 ms | median dt | "
          "unmatched 1024 | unmatched 512 |")
    print("|---|---|---|---|---|---|---|---|")
    tot = [0, 0, 0, 0, 0, 0]
    for t in tracks:
        a = measure(t, coarse, flags)["boom_at"]
        b = measure(t, fine, flags)["boom_at"]
        d = [min((abs(x - y) for y in b), default=9.9) for x in a]
        w12 = sum(1 for x in d if x <= 0.012)
        w23 = sum(1 for x in d if x <= 0.023)
        # The other direction: a hop-512 boom with no hop-1024 boom near it.
        e = [min((abs(y - x) for x in a), default=9.9) for y in b]
        u512 = sum(1 for x in e if x > 0.023)
        print(f"| {t.label} | {len(a)} | {len(b)} | {100*w12/max(1,len(a)):.0f}% | "
              f"{100*w23/max(1,len(a)):.0f}% | {1000*med(d):.0f} ms | "
              f"{len(a)-w23} | {u512} |")
        tot[0] += len(a); tot[1] += len(b); tot[2] += w12; tot[3] += w23
        tot[4] += len(a) - w23; tot[5] += u512
    print()
    print(f"totals: {tot[0]} booms at 1024, {tot[1]} at 512; "
          f"{100*tot[2]/max(1,tot[0]):.1f}% within one hop, "
          f"{100*tot[3]/max(1,tot[0]):.1f}% within one window; "
          f"{tot[4]} hop-1024 booms unmatched, {tot[5]} hop-512 booms new")


def main():
    """
    @brief Parse the subcommand and run it.
    @return Whatever the subcommand returns, which is None for all of them.
    """
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    def groups_arg(sp, default=("anchor", "breadth")):
        sp.add_argument("--groups", nargs="+", default=list(default),
                        choices=["anchor", "breadth", "control",
                                 "zabumba", "zabumba-speech"])

    m = sub.add_parser("manifest"); groups_arg(m); m.set_defaults(fn=cmd_manifest)
    c = sub.add_parser("control"); c.set_defaults(fn=cmd_control)
    b = sub.add_parser("baseline"); b.set_defaults(fn=cmd_baseline)

    g = sub.add_parser("segments")
    g.add_argument("--hop", type=int, default=512)
    g.add_argument("--window", type=float, default=1.0)
    g.add_argument("--rise", type=float, default=0.02)
    g.add_argument("--b1", type=float, default=0.004)
    g.add_argument("--min-run", type=float, default=3.0)
    g.add_argument("--min-seg", type=float, default=5.0)
    g.add_argument("--raw", action="store_true")
    g.set_defaults(fn=cmd_segments)

    l = sub.add_parser("label")
    l.add_argument("--track", help="substring of the recording name; default all")
    l.add_argument("--hop", type=int, default=512)
    l.add_argument("--out", default=str(CACHE / "clicks"))
    l.add_argument("--force", action="store_true",
                   help="regenerate candidates for a recording that already has labels")
    l.set_defaults(fn=cmd_label)

    s = sub.add_parser("sweep"); groups_arg(s)
    s.add_argument("--detector", choices=["boom", "beat"], default="boom")
    s.add_argument("--hop", type=int, default=512)
    s.add_argument("--hist", type=int)
    s.add_argument("--floors", type=float, nargs="+",
                   default=[0.012, 0.016, 0.02, 0.024, 0.028, 0.03, 0.06])
    s.set_defaults(fn=cmd_sweep)

    h = sub.add_parser("hist"); groups_arg(h)
    h.add_argument("--hop", type=int, default=512)
    h.add_argument("--hists", type=int, nargs="+", default=[22, 43, 64, 86])
    h.add_argument("--gap", type=int, default=10)
    h.set_defaults(fn=cmd_hist)

    i = sub.add_parser("instants")
    i.add_argument("--boom-floor", type=float)
    i.add_argument("--hist", type=int)
    i.set_defaults(fn=cmd_instants)

    args = p.parse_args()
    CACHE.mkdir(parents=True, exist_ok=True)
    args.fn(args)


## @cond
# The entry point, not API.
if __name__ == "__main__":
    main()
## @endcond
