/*
 * Bridge -> hub link, carrying undecoded SBC.
 *
 * SPI, from bt_bridge (master) to hub_s3 (slave). One link, and the only one.
 *
 * A UART link came first and was described here beside it, kept alive because
 * the classic `hub/` still spoke it. That project was retired on 2026-08-12 and
 * the UART declarations went with it. The comparisons below still argue against
 * the UART because that is where the SPI design's reasons come from -- read them
 * as history, not as a second option.
 *
 * Both ends share this header and must agree; change it here only.
 *
 * ---------------------------------------------------------------------------
 * WHY NOT I2S, AND WHY SPI IS NOT THE SAME MISTAKE
 * ---------------------------------------------------------------------------
 *
 * The first design sent decoded PCM over I2S and silently lost ~1.15% of
 * frames. Nine suspects were eliminated before the real one: the ESP32's I2S
 * SLAVE RECEIVER drops frames when sampling a clock generated by a different
 * chip's crystal. Everything on the wire was perfect; the peripheral did not
 * deliver what arrived at its pins.
 *
 * UART sidestepped the category entirely -- each byte resynchronises on its own
 * start bit, so no clock is shared. SPI does not have that property, and going
 * back to a clocked link is the obvious objection to this change. The answer is
 * that the two are clocked differently:
 *
 *   I2S is CONTINUOUS. The slave tracks a free-running foreign clock forever
 *        and has nothing to realign against; alignment error accumulates and
 *        there is no boundary at which it is discarded.
 *   SPI is TRANSACTIONAL. CS frames every transfer. The bit counter resets at
 *        each assertion, so nothing accumulates across frames -- the worst a
 *        clock difference can cost is one frame, and the CRC catches that one.
 *
 * That is an argument, not a measurement. `crc` in the sbc_in stats line is
 * what tests it, and it is expected to sit at 0. If it does not, this paragraph
 * is what was wrong.
 */
#pragma once

#include <stdint.h>

/* One A2DP packet can hold several SBC frames. Sized for the codec's own
 * SBC_MAX_BITPOOL (250) at any phone MTU, so the link never refuses a packet a
 * handset can actually produce. AUDIO_MAX_PAYLOAD in sync_proto.h is the same
 * ceiling on the WiFi hop to satellites and must stay >= this; test_sync_proto.c
 * asserts it does not drift below. */
#define SBC_LINK_MAX_PAYLOAD 2048

/*
 * Link payload kinds. Audio dominates; metadata is occasional.
 *
 * A packet's kind is carried in the header rather than inferred from length,
 * because SBC payloads vary in size and guessing would eventually be wrong.
 */
typedef enum {
    LINK_KIND_SBC  = 0,   /* one or more SBC frames */
    LINK_KIND_META = 1,   /* track metadata, see link_meta_t */
    LINK_KIND_VOL  = 2,   /* AVRCP absolute volume, see link_vol_t */
} link_kind_t;

/* ------------------------------------------------------------------------- */
/* The SPI link                                                              */
/* ------------------------------------------------------------------------- */

/*
 * Start slow and raise it once framing is proven.
 *
 * 1 MHz is already 20x the UART's 50 kB/s and carries the measured ~42 kB/s
 * stream at ~40% utilisation with the padding below included. 10 MHz is 1.25
 * MB/s, ~25x, and is where the bitpool question stops existing.
 *
 * The UART's ceiling was the leads rather than the protocol -- 500 kbaud was
 * where breadboard jumpers began producing bad sync bytes. SPI adds a clock
 * line to the same bundle, so expect the same wiring to set the same kind of
 * limit, and raise this in steps against the crc counter rather than in one go.
 *
 * Set through the DANCEFLOOR_SBC_LINK_SPI_HZ Kconfig symbol (default 1 MHz);
 * only the bridge build's value is on the wire, as the slave is clocked by it.
 */
#define SBC_LINK_SPI_HZ CONFIG_DANCEFLOOR_SBC_LINK_SPI_HZ

/*
 * CS is the framing.
 *
 * One CS assertion is exactly one frame, which is why there are no sync bytes
 * here. The UART header carried 0xA5 0x5A and the receiver scanned for them,
 * because a byte stream has no boundaries of its own; a resync scan, a
 * bad-sync counter and a false-sync branch all existed to serve that. None of
 * them has anything to do on this link.
 *
 * 12 bytes, so header + SBC_LINK_MAX_PAYLOAD stays a multiple of 4 -- the SPI
 * slave's DMA buffer must be 4-byte aligned with a length that is a multiple
 * of 4, and satisfying that in the type is better than remembering it at every
 * allocation.
 */
typedef struct __attribute__((packed)) {
    uint8_t  kind;        /* link_kind_t */
    uint8_t  rsv;
    uint16_t len;         /* payload bytes that are real; the rest is padding */
    uint32_t seq;         /* detects loss without needing a timer */
    uint16_t crc;         /* see sbc_link_crc16() -- covers header AND payload */
    uint16_t rsv2;
} spi_link_hdr_t;

/*
 * Every transaction is this size, padded, whatever the payload measures.
 *
 * A fixed size means both ends agree on the length BEFORE the transfer, so
 * nothing depends on the slave reporting how many bits it actually received --
 * a variable-length design has to trust trans_len, and a wrong answer there is
 * indistinguishable from corruption. The frame is sized for the codec's bitpool
 * ceiling, not today's payloads, so most of it is padding at low bitpool; at
 * 10 MHz that padding is free, and the fixed size is what makes a CS-split
 * transfer an unambiguous fault rather than a guess.
 */
#define SBC_LINK_FRAME_BYTES (sizeof(spi_link_hdr_t) + SBC_LINK_MAX_PAYLOAD)

/*
 * CRC-16/CCITT-FALSE over the header and the real payload, with `crc` zeroed.
 * The padding is not covered: it is uninitialised, and checking bytes nobody
 * sent would fail every frame.
 *
 * This replaces the UART link's XOR byte, and the reason is the sync words
 * going away. On the UART a corrupt `len` was caught by the resync scan
 * eventually finding the next real sync pair. Here `len` is checked against
 * nothing but this, and an 8-bit XOR misses every two-bit error and every
 * transposition -- cheap to outrun on a link running 20x faster.
 */
uint16_t sbc_link_crc16(const void *hdr, const void *payload, uint16_t len);

/* ------------------------------------------------------------------------- */
/* Carried by the link                                                       */
/* ------------------------------------------------------------------------- */

/*
 * Track metadata from AVRCP.
 *
 * `track_id` increments on every track-change notification, so a receiver can
 * tell "same song, metadata resent" from "new song" without comparing strings.
 * That distinction is what makes this usable as a re-anchor trigger later: a
 * track change is an unambiguous moment when a splice is inaudible, unlike
 * silence detection which can false-trigger on a quiet passage.
 *
 * Fixed-size fields rather than packed strings: trivially parsed, and a
 * truncated title is a better failure than a malformed packet.
 */
#define META_TEXT_LEN 64

typedef struct __attribute__((packed)) {
    uint32_t track_id;
    char     title[META_TEXT_LEN];
    char     artist[META_TEXT_LEN];
    char     album[META_TEXT_LEN];
} link_meta_t;

/*
 * Absolute volume from AVRCP, 0-127 by specification, 127 being unity.
 *
 * The bridge is the only unit the phone talks to, so it is the only one that
 * can hear this, and it forwards rather than acts: the speakers apply it, at
 * the output, in audio_apply_volume(). A whole SPI frame for one byte, which is
 * fine -- a volume change is a human moving a slider, not an audio-rate event.
 */
typedef struct __attribute__((packed)) {
    uint8_t volume;
} link_vol_t;

/*
 * Full scale, and the default everywhere. AVRCP fixes the range at 0-127, so
 * this is the specification's number rather than a choice.
 *
 * Here rather than in audio_out.h because all three projects need it and only
 * the speakers include that: the bridge reads sbc_link.h, and sync_proto.h --
 * which audio_out.h includes -- reads it too, so one definition reaches
 * everything. A unit that has never been told a volume uses this, which is why
 * a missed message plays loud rather than silent.
 */
#define AUDIO_VOL_MAX 127
