/**
 * @file sbc_link.h
 * @brief Bridge -> hub link, carrying undecoded SBC. SPI, from bt_bridge
 *        (master) to hub_s3 (slave). One link, and the only one.
 *
 * Both ends share this header and must agree; change it here only.
 *
 * WHY NOT I2S, AND WHY SPI IS NOT THE SAME MISTAKE. An earlier design sent
 * decoded PCM over I2S and silently lost about one frame in a hundred. The
 * cause was the peripheral rather than the wire: the ESP32's I2S SLAVE
 * RECEIVER drops frames when sampling a clock generated by a different chip's
 * crystal, so everything on the wire was correct and the peripheral did not
 * deliver what arrived at its pins. Going back to a clocked link is the
 * obvious objection to SPI, and the answer is that the two are clocked
 * differently:
 *
 *   I2S is CONTINUOUS. The slave tracks a free-running foreign clock forever
 *        and has nothing to realign against, so alignment error accumulates
 *        and there is no boundary at which it is discarded.
 *   SPI is TRANSACTIONAL. CS frames every transfer, so the bit counter resets
 *        at each assertion and nothing accumulates across frames. The worst a
 *        clock difference can cost is one frame, and the CRC catches that one.
 *
 * That argument has since been measured across many hours and millions of
 * packets: the hub reports zero bad headers, zero CRC failures and zero
 * CS-split transfers. What it does NOT cover is packets that never arrive at
 * all -- those are lost before the wire, and sbc_in.c's `lost` counter says
 * how many while bt_bridge's own counters say whose.
 */
#pragma once

#include <stdint.h>

/**
 * @brief The largest SBC payload one link frame may carry.
 *
 * Sized for the codec's own maximum bitpool at any phone MTU, so the link
 * never refuses a packet a handset can actually produce. AUDIO_MAX_PAYLOAD in
 * sync_proto.h is the same ceiling on the WiFi hop to the satellites and must
 * stay at least this large; test_sync_proto.c asserts it does not drift below.
 */
#define SBC_LINK_MAX_PAYLOAD 2048

/**
 * @brief Link payload kinds. Audio dominates; the rest are occasional.
 *
 * A packet's kind is carried in the header rather than inferred from its
 * length, because SBC payloads vary in size and guessing would eventually be
 * wrong.
 */
typedef enum {
    LINK_KIND_SBC  = 0,   /**< One or more SBC frames. */
    LINK_KIND_META = 1,   /**< Track metadata; see link_meta_t. */
    LINK_KIND_VOL  = 2,   /**< AVRCP absolute volume; see link_vol_t. */
} link_kind_t;

/**
 * @brief SPI clock for the link, from the DANCEFLOOR_SBC_LINK_SPI_HZ Kconfig
 *        symbol.
 *
 * Only the bridge build's value is on the wire, since the slave is clocked by
 * it. Start slow and raise it in steps against the CRC counter rather than in
 * one go: the practical ceiling is the wiring rather than the protocol, and
 * SPI adds a clock line to the same bundle that limited the link this
 * replaced.
 */
#define SBC_LINK_SPI_HZ CONFIG_DANCEFLOOR_SBC_LINK_SPI_HZ

/**
 * @brief The link frame header. CS is the framing, so there are no sync bytes.
 *
 * One CS assertion is exactly one frame. A byte-stream link has no boundaries
 * of its own and needs a sync word, a resync scan, a bad-sync counter and a
 * false-sync branch; none of those has anything to do here.
 *
 * Twelve bytes, so that header + SBC_LINK_MAX_PAYLOAD stays a multiple of
 * four: the SPI slave's DMA buffer must be 4-byte aligned with a length that
 * is a multiple of four, and satisfying that in the type is better than
 * remembering it at every allocation.
 */
typedef struct __attribute__((packed)) {
    uint8_t  kind;        /**< link_kind_t. */
    uint8_t  rsv;         /**< Padding; not interpreted. */
    uint16_t len;         /**< Payload bytes that are real; the rest is padding. */
    uint32_t seq;         /**< Detects loss without needing a timer. */
    uint16_t crc;         /**< See sbc_link_crc16(); covers header AND payload. */
    uint16_t rsv2;        /**< Padding, to the 4-byte multiple above. */
} spi_link_hdr_t;

/**
 * @brief Every transaction is this size, padded, whatever the payload measures.
 *
 * A fixed size means both ends agree on the length BEFORE the transfer, so
 * nothing depends on the slave reporting how many bits it actually received --
 * a variable-length design has to trust that report, and a wrong answer there
 * is indistinguishable from corruption. The frame is sized for the codec's
 * bitpool ceiling rather than for today's payloads, so most of it is padding
 * at low bitpool; that padding is what makes a CS-split transfer an
 * unambiguous fault rather than a guess.
 */
#define SBC_LINK_FRAME_BYTES (sizeof(spi_link_hdr_t) + SBC_LINK_MAX_PAYLOAD)

/**
 * @brief CRC-16/CCITT-FALSE over the header and the real payload, with the
 *        `crc` field taken as zero.
 *
 * The padding is deliberately not covered: it is uninitialised, and checking
 * bytes nobody sent would fail every frame.
 *
 * A 16-bit CRC rather than the XOR byte a sync-word link can get away with.
 * There, a corrupt length is caught eventually by the resync scan finding the
 * next real sync pair; here `len` is checked against nothing but this, and an
 * 8-bit XOR misses every two-bit error and every transposition.
 *
 * @param hdr      The frame header. Header and payload are separate arguments
 *                 because they are separate buffers at both ends and always
 *                 will be: the bridge builds a header around a pointer the
 *                 Bluetooth stack owns, and the hub checks the frame before it
 *                 has decided the payload is real.
 * @param payload  The payload bytes.
 * @param len      How many of them are real.
 * @return The CRC to write into, or compare against, spi_link_hdr_t::crc.
 */
uint16_t sbc_link_crc16(const void *hdr, const void *payload, uint16_t len);

/** @brief Fixed width of each metadata text field, including its terminator. */
#define META_TEXT_LEN 64

/**
 * @brief Track metadata from AVRCP.
 *
 * Fixed-size fields rather than packed strings: trivially parsed, and a
 * truncated title is a better failure than a malformed packet.
 */
typedef struct __attribute__((packed)) {
    /** @brief Increments on every track-change notification, so a receiver can
     *         tell "same song, metadata resent" from "new song" without
     *         comparing strings. That distinction is what makes this usable as
     *         a re-anchor trigger: a track change is an unambiguous moment when
     *         a splice is inaudible, unlike silence detection, which
     *         false-triggers on a quiet passage. */
    uint32_t track_id;
    char     title[META_TEXT_LEN];   /**< Truncated to fit; may be empty. */
    char     artist[META_TEXT_LEN];  /**< Likewise. */
    char     album[META_TEXT_LEN];   /**< Likewise. */
} link_meta_t;

/**
 * @brief Absolute volume from AVRCP.
 *
 * The bridge is the only unit the phone talks to, so it is the only one that
 * can hear this, and it forwards rather than acts: the speakers apply it at
 * their output, in audio_volume_write_i32(). A whole SPI frame for one byte,
 * which is fine -- a volume change is a human moving a slider, not an
 * audio-rate event.
 */
typedef struct __attribute__((packed)) {
    uint8_t volume;   /**< 0..AUDIO_VOL_MAX. */
} link_vol_t;

/**
 * @brief Full scale. AVRCP fixes the range at 0-127, so this is the
 *        specification's number rather than a choice.
 *
 * Here rather than in audio_out.h because all three projects need it and only
 * the speakers include that: the bridge reads sbc_link.h, and sync_proto.h --
 * which audio_out.h includes -- reads it too, so one definition reaches
 * everything.
 *
 * IT IS NOT THE DEFAULT ON A SPEAKER. A unit that has never been told a level
 * plays SILENCE and keeps this only as a bounded fallback; see
 * audio_vol_effective() in audio_out.h for why the two failure modes are not
 * symmetrical. It remains the bridge's default, where it means something
 * different and harmless: the bridge has no DAC, so this is only the value it
 * forwards and answers AVRCP interim notifications with until the phone states
 * one.
 */
#define AUDIO_VOL_MAX 127
