#!/usr/bin/env python3
import argparse
import math

VOL_MAX = 127
FLOOR_DB = -60.0
UNITY = 65536


def gain(v):
    if v <= 0:
        return 0
    if v >= VOL_MAX:
        return UNITY
    db = FLOOR_DB * (VOL_MAX - v) / (VOL_MAX - 1)
    return round(UNITY * 10 ** (db / 20))


def table():
    return [gain(v) for v in range(VOL_MAX + 1)]


def emit():
    t = table()
    step_db = -FLOOR_DB / (VOL_MAX - 1)
    print("    /* Generated by tools/gen_vol_table.py -- do not hand-edit.")
    print("     * %.1f dB at 1 up to unity at %d, %.4f dB a step, 0 = hard mute."
          % (FLOOR_DB, VOL_MAX, step_db))
    print("     * test_sync_proto.c re-derives that relationship rather than")
    print("     * trusting these digits, so an edited entry fails there. */")
    for i in range(0, len(t), 8):
        row = ", ".join("%6d" % g for g in t[i:i + 8])
        print("    %s," % row)


def check():
    t = table()
    print("v      q16        dB   step dB")
    for v in range(VOL_MAX + 1):
        db = float("-inf") if t[v] == 0 else 20 * math.log10(t[v] / UNITY)
        step = "" if v < 2 else "%8.4f" % (20 * math.log10(t[v] / t[v - 1]))
        print("%3d %8d %9.3f %s" % (v, t[v], db, step))
    assert all(t[v] > t[v - 1] for v in range(2, VOL_MAX + 1)), "not monotonic"
    assert t[0] == 0 and t[VOL_MAX] == UNITY
    worst = max(abs(x) * max(t) for x in (-32768, 32767))
    assert worst <= 2 ** 31, worst
    print("\nstrictly monotonic; endpoints exact; |in*g| <= 2^31 at the extremes")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    check() if a.check else emit()
