#!/usr/bin/env python3
"""
Generate the volume taper table in audio_out.h.

The taper is LINEAR IN dB: every step of the AVRCP level is the same number of
decibels, from FLOOR_DB at 1 up to unity at AUDIO_VOL_MAX. That is the whole
design, and it is why the table is generated rather than written -- the property
worth having is a relationship, and a relationship is easy to break by hand.

It replaced a square law, which spent the slider unevenly: measured against the
levels a phone actually sends (it steps in multiples of five), one click near the
bottom was a 4-7 dB jump and one click near the top was half a decibel. The
useful range was all crammed into the bottom of the travel, which is exactly
where a square law has the least resolution to give.

Floats live here and never in the firmware. The hub is an LX7 and the satellite
an LX6, and a float evaluated on both could round differently and put the same
stream out at two levels -- the same class of fault as the two disagreeing about
rate. A constant table cannot: it is the same bytes in both images.

    tools/gen_vol_table.py            # print the C literal for audio_out.h
    tools/gen_vol_table.py --check    # print the dB the table actually realises

Q16, unity 65536, because that is what makes the widening multiply in
audio_volume_write_i32() exact: unity becomes a shift of 16 and nothing is
discarded at any level. See audio_out.h.
"""
import argparse
import math

VOL_MAX = 127        # AVRCP's own range, sbc_link.h
FLOOR_DB = -60.0     # the level at 1; 0 is a hard mute and is not on the curve
UNITY = 65536        # q16


def gain(v):
    """The q16 gain for level v."""
    if v <= 0:
        return 0
    if v >= VOL_MAX:
        return UNITY
    db = FLOOR_DB * (VOL_MAX - v) / (VOL_MAX - 1)
    return round(UNITY * 10 ** (db / 20))


def table():
    return [gain(v) for v in range(VOL_MAX + 1)]


def emit():
    t = table()
    step_db = -FLOOR_DB / (VOL_MAX - 1)
    print("    /* Generated by tools/gen_vol_table.py -- do not hand-edit.")
    print("     * %.1f dB at 1 up to unity at %d, %.4f dB a step, 0 = hard mute."
          % (FLOOR_DB, VOL_MAX, step_db))
    print("     * test_sync_proto.c re-derives that relationship rather than")
    print("     * trusting these digits, so an edited entry fails there. */")
    for i in range(0, len(t), 8):
        row = ", ".join("%6d" % g for g in t[i:i + 8])
        print("    %s," % row)


def check():
    t = table()
    print("v      q16        dB   step dB")
    for v in range(VOL_MAX + 1):
        db = float("-inf") if t[v] == 0 else 20 * math.log10(t[v] / UNITY)
        step = "" if v < 2 else "%8.4f" % (20 * math.log10(t[v] / t[v - 1]))
        print("%3d %8d %9.3f %s" % (v, t[v], db, step))
    assert all(t[v] > t[v - 1] for v in range(2, VOL_MAX + 1)), "not monotonic"
    assert t[0] == 0 and t[VOL_MAX] == UNITY
    # The bound the exactness argument in audio_out.h rests on.
    worst = max(abs(x) * max(t) for x in (-32768, 32767))
    assert worst <= 2 ** 31, worst
    print("\nstrictly monotonic; endpoints exact; |in*g| <= 2^31 at the extremes")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    check() if a.check else emit()
